language: ruby

addons:
  code_climate:
    repo_token: 17abb3979e6abb0cee4069ec3e7aeee9c6e4fd8277b0899b4cd0900ac6030f98

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.2
  - rbx-2.2.6
  - jruby

matrix:
  allow_failures: 
    - rvm: rbx-2.2.6
    - rvm: jruby
